repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: mypy
        types: [python]
        pass_filenames: false

      - id: ruff_lint
        name: ruff lint
        stages: [commit]
        language: system
        entry: ruff check
        types: [python]
        pass_filenames: false

      - id: ruff_format
        name: ruff format
        stages: [commit]
        language: system
        entry: ruff format
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pytest
        types: [python]