[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "project-template"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
isort = "^4.3.21"
mypy = "^0.761"
pre-commit = "^1.21.0"
pytest = "^5.3.2"
pytest-cov = "^2.8.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry_core>=1.0.0"]

[tool.black]
