[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "project-template"
version = "0.1.0"

[tool.poetry.dependencies]
pydantic = "^1.6.1"
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.3"
isort = "^5.5.1"
mypy = "^0.782"
pre-commit = "^2.7.1"
pytest = "^6.0.1"
pytest-cov = "2.10.1"

[tool.pytest.ini_options]
addopts = "--cov={{cookiecutter.repo_name}} tests/ --cov-fail-under=100 --cov-report html"
testpaths = "tests/"

[tool.isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=88


[tool.black]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry_core>=1.0.0"]
